import type { Visit, Evidence, TimelineEvent } from "@/types/visits"

// Mock evidence data
const mockEvidence: Evidence[] = [
  {
    id: "evidence-001",
    visitId: "visit-002",
    type: "photo",
    url: "/citizen-welfare-check-photo.png",
    filename: "citizen_welfare_check_001.jpg",
    description: "Senior citizen at home, appears healthy and well",
    lat: 28.6139,
    lng: 77.2295,
    takenAt: "2024-01-18T10:30:00Z",
    uploadedBy: "officer-001",
    uploadedByName: "Constable Raj Singh",
  },
  {
    id: "evidence-002",
    visitId: "visit-002",
    type: "photo",
    url: "/home-condition-check-photo.png",
    filename: "home_condition_001.jpg",
    description: "Home environment check - clean and safe",
    lat: 28.6139,
    lng: 77.2295,
    takenAt: "2024-01-18T10:35:00Z",
    uploadedBy: "officer-001",
    uploadedByName: "Constable Raj Singh",
  },
  {
    id: "evidence-003",
    visitId: "visit-003",
    type: "photo",
    url: "/medical-check-documentation-photo.png",
    filename: "medical_check_001.jpg",
    description: "Citizen showing medication, health status good",
    lat: 28.6328,
    lng: 77.2197,
    takenAt: "2024-01-19T11:15:00Z",
    uploadedBy: "officer-002",
    uploadedByName: "Constable Priya Sharma",
  },
]

// Mock timeline events
const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "timeline-001",
    visitId: "visit-001",
    type: "assigned",
    description: "Visit assigned to Constable Raj Singh for Janpath Beat 1",
    performedBy: "sho-001",
    performedByName: "SHO Amit Sharma",
    timestamp: "2024-01-17T09:00:00Z",
  },
  {
    id: "timeline-002",
    visitId: "visit-002",
    type: "assigned",
    description: "Visit assigned to Constable Raj Singh for Janpath Beat 1",
    performedBy: "sho-001",
    performedByName: "SHO Amit Sharma",
    timestamp: "2024-01-17T09:00:00Z",
  },
  {
    id: "timeline-003",
    visitId: "visit-002",
    type: "checkin",
    description: "Officer checked in at citizen location",
    performedBy: "officer-001",
    performedByName: "Constable Raj Singh",
    timestamp: "2024-01-18T10:25:00Z",
  },
  {
    id: "timeline-004",
    visitId: "visit-002",
    type: "evidence_added",
    description: "Added welfare check photos and home condition documentation",
    performedBy: "officer-001",
    performedByName: "Constable Raj Singh",
    timestamp: "2024-01-18T10:40:00Z",
  },
  {
    id: "timeline-005",
    visitId: "visit-002",
    type: "completed",
    description: "Visit completed successfully - citizen welfare confirmed",
    performedBy: "officer-001",
    performedByName: "Constable Raj Singh",
    timestamp: "2024-01-18T11:00:00Z",
  },
  {
    id: "timeline-006",
    visitId: "visit-003",
    type: "assigned",
    description: "Visit assigned to Constable Priya Sharma for Rajiv Chowk Beat 1",
    performedBy: "sho-001",
    performedByName: "SHO Amit Sharma",
    timestamp: "2024-01-18T08:00:00Z",
  },
  {
    id: "timeline-007",
    visitId: "visit-003",
    type: "checkin",
    description: "Officer checked in at citizen location",
    performedBy: "officer-002",
    performedByName: "Constable Priya Sharma",
    timestamp: "2024-01-19T11:00:00Z",
  },
  {
    id: "timeline-008",
    visitId: "visit-003",
    type: "evidence_added",
    description: "Added medical status check and medication verification photos",
    performedBy: "officer-002",
    performedByName: "Constable Priya Sharma",
    timestamp: "2024-01-19T11:20:00Z",
  },
  {
    id: "timeline-009",
    visitId: "visit-003",
    type: "completed",
    description: "Visit completed - citizen health status verified",
    performedBy: "officer-002",
    performedByName: "Constable Priya Sharma",
    timestamp: "2024-01-19T11:30:00Z",
  },
  {
    id: "timeline-010",
    visitId: "visit-003",
    type: "approved",
    description: "Visit approved by SHO - all documentation complete",
    performedBy: "sho-001",
    performedByName: "SHO Amit Sharma",
    timestamp: "2024-01-19T16:00:00Z",
  },
]

// Mock visits data
export const mockVisits: Visit[] = [
  {
    id: "visit-001",
    citizenId: "citizen-001",
    citizenName: "Shri Ram Kumar Sharma",
    citizenPhoto: "/indian-man-profile.png",
    citizenAddress: "A-123, Connaught Place, New Delhi - 110001",
    citizenLat: 28.6315,
    citizenLng: 77.2167,
    vulnerabilityScore: 85,
    stationId: "station-001",
    stationName: "Connaught Place Police Station",
    postId: "post-001",
    postName: "Janpath Chowki",
    beatId: "beat-001",
    beatName: "Janpath Beat 1",
    assignedOfficerId: "officer-001",
    assignedOfficerName: "Constable Raj Singh",
    status: "scheduled",
    priority: "high",
    scheduledAt: "2024-01-20T09:00:00Z",
    timeline: mockTimelineEvents.filter((t) => t.visitId === "visit-001"),
    notes: "High priority senior citizen, lives alone, requires regular welfare checks",
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-17T09:00:00Z",
  },
  {
    id: "visit-002",
    citizenId: "citizen-002",
    citizenName: "Smt. Kamala Devi",
    citizenPhoto: "/indian-woman-profile-photo.png",
    citizenAddress: "B-456, Janpath, New Delhi - 110001",
    citizenLat: 28.6139,
    citizenLng: 77.2295,
    vulnerabilityScore: 72,
    stationId: "station-001",
    stationName: "Connaught Place Police Station",
    postId: "post-001",
    postName: "Janpath Chowki",
    beatId: "beat-001",
    beatName: "Janpath Beat 1",
    assignedOfficerId: "officer-001",
    assignedOfficerName: "Constable Raj Singh",
    status: "completed",
    priority: "medium",
    scheduledAt: "2024-01-18T10:00:00Z",
    checkinAt: "2024-01-18T10:25:00Z",
    completedAt: "2024-01-18T11:00:00Z",
    evidence: mockEvidence.filter((e) => e.visitId === "visit-002"),
    timeline: mockTimelineEvents.filter((t) => t.visitId === "visit-002"),
    notes: "Regular welfare check, citizen has family support",
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-18T11:00:00Z",
  },
  {
    id: "visit-003",
    citizenId: "citizen-003",
    citizenName: "Shri Mohan Lal Gupta",
    citizenPhoto: "/indian-man-profile.png",
    citizenAddress: "C-789, Rajiv Chowk, New Delhi - 110001",
    citizenLat: 28.6328,
    citizenLng: 77.2197,
    vulnerabilityScore: 91,
    stationId: "station-001",
    stationName: "Connaught Place Police Station",
    postId: "post-002",
    postName: "Rajiv Chowk Chowki",
    beatId: "beat-003",
    beatName: "Rajiv Chowk Beat 1",
    assignedOfficerId: "officer-002",
    assignedOfficerName: "Constable Priya Sharma",
    status: "approved",
    priority: "high",
    scheduledAt: "2024-01-19T11:00:00Z",
    checkinAt: "2024-01-19T11:00:00Z",
    completedAt: "2024-01-19T11:30:00Z",
    approvedAt: "2024-01-19T16:00:00Z",
    approvedBy: "sho-001",
    approvalNotes: "Excellent documentation, citizen welfare confirmed",
    evidence: mockEvidence.filter((e) => e.visitId === "visit-003"),
    timeline: mockTimelineEvents.filter((t) => t.visitId === "visit-003"),
    notes: "High vulnerability score, medical conditions require monitoring",
    createdAt: "2024-01-18T08:00:00Z",
    updatedAt: "2024-01-19T16:00:00Z",
  },
  {
    id: "visit-004",
    citizenId: "citizen-004",
    citizenName: "Smt. Sunita Agarwal",
    citizenPhoto: "/indian-woman-profile-photo.png",
    citizenAddress: "D-321, Karol Bagh, New Delhi - 110005",
    citizenLat: 28.6519,
    citizenLng: 77.1909,
    vulnerabilityScore: 68,
    stationId: "station-003",
    stationName: "Karol Bagh Police Station",
    postId: "post-003",
    postName: "Ajmal Khan Road Chowki",
    beatId: "beat-004",
    beatName: "Karol Bagh Beat 1",
    assignedOfficerId: "officer-003",
    assignedOfficerName: "Constable Amit Verma",
    status: "in_progress",
    priority: "medium",
    scheduledAt: "2024-01-20T14:00:00Z",
    checkinAt: "2024-01-20T14:05:00Z",
    timeline: [
      {
        id: "timeline-011",
        visitId: "visit-004",
        type: "assigned",
        description: "Visit assigned to Constable Amit Verma for Karol Bagh Beat 1",
        performedBy: "sho-002",
        performedByName: "SHO Karol Bagh",
        timestamp: "2024-01-19T10:00:00Z",
      },
      {
        id: "timeline-012",
        visitId: "visit-004",
        type: "checkin",
        description: "Officer checked in at citizen location",
        performedBy: "officer-003",
        performedByName: "Constable Amit Verma",
        timestamp: "2024-01-20T14:05:00Z",
      },
    ],
    notes: "Routine welfare check, citizen has good community support",
    createdAt: "2024-01-19T10:00:00Z",
    updatedAt: "2024-01-20T14:05:00Z",
  },
  {
    id: "visit-005",
    citizenId: "citizen-005",
    citizenName: "Shri Rajesh Kumar",
    citizenPhoto: "/indian-man-profile.png",
    citizenAddress: "E-654, Green Park, New Delhi - 110016",
    citizenLat: 28.5494,
    citizenLng: 77.2001,
    vulnerabilityScore: 45,
    stationId: "station-004",
    stationName: "Hauz Khas Police Station",
    postId: "post-004",
    postName: "Green Park Chowki",
    beatId: "beat-005",
    beatName: "Green Park Beat 1",
    assignedOfficerId: "officer-004",
    assignedOfficerName: "Constable Sunita Patel",
    status: "overdue",
    priority: "low",
    scheduledAt: "2024-01-15T10:00:00Z", // Overdue
    timeline: [
      {
        id: "timeline-013",
        visitId: "visit-005",
        type: "assigned",
        description: "Visit assigned to Constable Sunita Patel for Green Park Beat 1",
        performedBy: "sho-003",
        performedByName: "SHO Hauz Khas",
        timestamp: "2024-01-14T09:00:00Z",
      },
    ],
    notes: "Low priority citizen, independent living, missed scheduled visit",
    createdAt: "2024-01-14T09:00:00Z",
    updatedAt: "2024-01-14T09:00:00Z",
  },
]

export function getVisitStats(visits: Visit[]): import("@/types/visits").VisitStats {
  const now = new Date()

  return {
    total: visits.length,
    scheduled: visits.filter((v) => v.status === "scheduled").length,
    inProgress: visits.filter((v) => v.status === "in_progress").length,
    completed: visits.filter((v) => v.status === "completed").length,
    approved: visits.filter((v) => v.status === "approved").length,
    overdue: visits.filter((v) => {
      if (v.status === "overdue") return true
      if (v.status === "scheduled" && new Date(v.scheduledAt) < now) return true
      return false
    }).length,
    highPriority: visits.filter((v) => v.priority === "high").length,
  }
}
